# Generated by Django 6.0.6 on 2026-06-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Critical'), (1, 'High'), (2, 'Medium'), (3, 'Low')], default=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting_user', 'Waiting user'), ('closed', 'Closed')], default='open', max_length=50),
        ),
    ]
