# Generated by Django 6.0.6 on 2026-06-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_priority_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_waiting_for_simulated_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_reply_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
