# Generated by Django 6.0.6 on 2026-06-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_is_waiting_for_simulated_reply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('tickets_closed', models.IntegerField(default=0)),
                ('replies_sent', models.IntegerField(default=0)),
                ('user_replies_received', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
