# Generated by Django 6.0.6 on 2026-06-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_gamestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting_user', 'Waiting user'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='open', max_length=50),
        ),
    ]
