# Generated by Django 6.0.6 on 2026-06-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='simulation_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('priority_changed', 'Priority changed'), ('marked_duplicate', 'Marked duplicate'), ('unmarked_duplicate', 'Unmarked duplicate'), ('message_sent', 'Message sent'), ('user_reply', 'User reply'), ('note', 'Internal note'), ('score', 'Score')], max_length=50),
        ),
    ]
