# Generated by Django 5.2.15 on 2026-07-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_gamestate_simulation_running_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='speed',
            field=models.CharField(choices=[('relaxed', 'Relaxed'), ('normal', 'Normal'), ('fast', 'Fast')], default='normal', max_length=16),
        ),
    ]
